//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.InfOrder = new HashSet<InfOrder>();
        }
    
        public int Book_number { get; set; }
        public int Author_id { get; set; }
        public int Publisher_id { get; set; }
        public string Book_name { get; set; }
        public System.DateTime Pubyear { get; set; }
        public string Genre { get; set; }
        public int Price { get; set; }
        public int Amount_book { get; set; }
        public byte[] Image_book { get; set; }
    
        public virtual authors authors { get; set; }
        public virtual publishers publishers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfOrder> InfOrder { get; set; }
    }
}
